POST http://localhost:10099/testByJson
Content-Type: application/json

{
  "username":"sa",
  "password":"123fff",
  "captcha":"abcd",
  "createDate":"2019-08-05 11:34:31"
}

###
POST http://localhost:10099/testByMvc
Content-Type:application/x-www-form-urlencoded

username=sa&password=123333&captcha=abcd&createDate=2019-08-05 11:34:31

